[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "skahanium", email = "skahanium@gmail.com"},
]
dependencies = [
    "mkdocs>=1.4.2",
    "mkdocs-material>=9.0.11",
]
requires-python = ">=3.10"
license = {text = "MIT"}
