[project]
name = ""
version = ""
description = ""
authors = [
    {name = "skahanium", email = "skahanium@gmail.com"},
]
dependencies = [
    "mkdocs>=1.5.3",
    "mkdocs-material>=9.4.14",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

